name: Build First Python GUI App using TKinter

on:
  push:
    branches:
      - main  # change if your main branch is 'master'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build exe
      run: pyinstaller --onefile --windowed WelcomeFrame.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoffeeMachineExe
        path: dist/WelcomeFrame.exe
